<?php
$dolibarr_main_url_root='https://dolibarr-ex3d.onrender.com';
$dolibarr_main_document_root='/var/www/html/htdocs';
$dolibarr_main_data_root='/var/www/html/documents';
$dolibarr_main_db_host='db.pflklctzvmttqdpprota.supabase.co';
$dolibarr_main_db_port='6543';
$dolibarr_main_db_name='postgres';
$dolibarr_main_db_user='postgres';
$dolibarr_main_db_pass='AUREOX_2022';
$dolibarr_main_db_type='pgsql';
$force_install_no_directory_lock=1;
